version: '3' 
services:
  # db:
  #   image: mariadb
  #   container_name: covtrack_db
  #   hostname: covtrack_db
  #   volumes:
  #     - "/var/mariadb_covtrack/:/var/lib/mysql"
  #   ports:
  #     - "3307:3306"
  #   restart: on-failure:5
  #   environment:
  #     MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
  #     MYSQL_DATABASE: $MYSQL_DATABASE
  #     MYSQL_USER: $MYSQL_USER
  #     MYSQL_PASSWORD: $MYSQL_PASSWORD

  app:
    image: mual/covtrack
    container_name: covtrack
    hostname: covtrack
    #build: 
    #  context: .
    ports: 
      - 5001:5000
    restart: on-failure:5
    environment: 
      MYSQL_HOST: $MYSQL_HOST
      MYSQL_PORT: 3306
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      # FLASK_DEBUG: $FLASK_DEBUG
      FLASK_ENV: $FLASK_ENV
      PYTHONUNBUFFERED: $PYTHONUNBUFFERED
    # depends_on: 
    #   - db
